# Generated by Django 3.2.8 on 2021-12-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='abhi', max_length=50),
        ),
    ]
